build.gradle
gradle.properties
src/main/resources/application.properties

- parametrize server.port
- set  jar task dependency on webpack

MOTS-22 Set up demo instance

---

package.json
src/webapp/css/dimensions.scss
src/webapp/css/main.scss
src/webapp/js/components/app.js
src/webapp/js/components/assign-modules.js
src/webapp/js/components/sidebar.js
src/webapp/js/container/chw-table.js

Assigning CHW to Modules Screen

MOTS-17 Initial

---

src/webapp/js/components/assign-modules.js

- Send request when initiating view to fetch CHW and his modules
- Populating left-side box with already assigned modules

MOTS-52 Improve CHW Module Assignment view

---

src/webapp/js/components/health-workers-new.js
src/webapp/js/components/health-workers.js

- adding page-header class to CHW form

---

src/webapp/js/components/assign-modules.js
src/webapp/js/components/health-workers-new.js

-initiate names in grid

---

src/main/java/org/motechproject/mots/domain/AssignedModules.java
src/main/java/org/motechproject/mots/service/CommunityHealthWorkerService.java

when AssignedModules weren't initiated on create CHW action.

Fixed bug happening on assigning modules page, which happened

---

src/webapp/js/components/assign-modules.js

-replace nulls with empty string

-pick only names from chw for now

---

build.gradle
package.json
src/main/java/org/motechproject/mots/security/AuthorizationServerConfiguration.java
src/main/java/org/motechproject/mots/security/CustomTokenEnhancer.java
src/main/java/org/motechproject/mots/security/ResourceServerConfiguration.java
src/webapp/js/actions/index.js
src/webapp/js/components/auth/authenticate_token.js
src/webapp/js/components/auth/require_auth.js
src/webapp/js/index.js
src/webapp/js/reducers/auth_reducer.js

- signout if jwt token expires
- tide up index.js

MOTS-55 Use JWT token

---

mobile/components/Collapsible.js
mobile/components/Menu.js
mobile/package.json

plus included all missing items
https://applab.atlassian.net/browse/MOTS-135

Collapsible sections in menu

---

src/webapp/js/components/assign-modules.js
src/webapp/js/components/auth/require_auth.js
src/webapp/js/components/health-workers-edit.js
src/webapp/js/components/incharge-edit.js
src/webapp/js/container/chw-table.js
src/webapp/js/container/incharge-table.js

-add else to not trigger action in componentWillMount if no authority
-don't render if this.props.authenticated is false

MOTS-61 fixes

---

mobile/actions/index.js
mobile/utils/api-client.js
mobile/utils/auth-client.js

https://applab.atlassian.net/browse/MOTS-158

Error handling in mobile app.

---

mobile/components/Menu.js

https://applab.atlassian.net/browse/MOTS-174

Logout button in mobile app.

---

build.gradle

Add JasperReports Library with 6.5.0 version to gradle file.
https://applab.atlassian.net/browse/MOTS-200

MOTS-200: Add JasperReports Library to gradle file

---

src/main/java/org/motechproject/mots/domain/JasperTemplate.java
src/main/java/org/motechproject/mots/domain/JasperTemplateParameter.java
src/main/java/org/motechproject/mots/repository/JasperTemplateRepository.java
src/main/resources/db/changelog/20180212_1645.mysql.sql
src/main/resources/db/changelog/liquibase-changelog.xml

Added jasper reports class models, created migration and added repository.
https://applab.atlassian.net/browse/MOTS-220

MOTS-220: Added jasper reports class models

---

build.gradle
src/main/java/org/motechproject/mots/constants/ReportingMessages.java
src/main/java/org/motechproject/mots/domain/JasperTemplate.java
src/main/java/org/motechproject/mots/domain/JasperTemplateParameter.java
src/main/java/org/motechproject/mots/dto/JasperTemplateDto.java
src/main/java/org/motechproject/mots/dto/JasperTemplateParameterDto.java
src/main/java/org/motechproject/mots/exception/BaseFormattedException.java
src/main/java/org/motechproject/mots/exception/EntityNotFoundException.java
src/main/java/org/motechproject/mots/exception/JasperReportViewException.java
src/main/java/org/motechproject/mots/exception/ReportingException.java
src/main/java/org/motechproject/mots/mapper/JasperTemplateMapper.java
src/main/java/org/motechproject/mots/mapper/JasperTemplateParameterMapper.java
src/main/java/org/motechproject/mots/repository/JasperTemplateRepository.java
src/main/java/org/motechproject/mots/service/JasperReportsViewService.java
src/main/java/org/motechproject/mots/service/JasperTemplateService.java
src/main/java/org/motechproject/mots/utils/ReportingValidationHelper.java
src/main/java/org/motechproject/mots/validate/annotations/Uuid.java
src/main/java/org/motechproject/mots/web/JasperTemplateController.java
src/main/resources/db/changelog/20180214_1622.mysql.sql
src/main/resources/db/changelog/liquibase-changelog.xml
src/test/java/org/motechproject/mots/repository/BaseCrudRepositoryIntegrationTest.java
src/test/java/org/motechproject/mots/repository/JasperTemplateRepositoryIntegrationTest.java
src/test/java/org/motechproject/mots/service/JasperTemplateServiceTest.java

MOTS-221, MOTS-222, MOTS-224, MOTS-225

MOTS-221: Add endpoints and services for storing and generating reports

---

mobile/components/ListItems.js
mobile/components/Menu.js
mobile/container/HealthWorkersList.js
mobile/container/InchargeList.js
mobile/utils/authorization.js
mobile/utils/form-utils.js

 MOTS-227: Handling user permissions in menu items

---

src/main/java/org/motechproject/mots/domain/Facility.java
src/main/java/org/motechproject/mots/errorhandling/GlobalErrorHandling.java
src/main/java/org/motechproject/mots/repository/CommunityHealthWorkerRepository.java
src/main/java/org/motechproject/mots/repository/custom/CommunityHealthWorkerRepositoryCustom.java
src/main/java/org/motechproject/mots/repository/custom/impl/CommunityHealthWorkerRepositoryImpl.java
src/main/java/org/motechproject/mots/service/CommunityHealthWorkerService.java
src/main/java/org/motechproject/mots/web/CommunityHealthWorkerController.java
src/test/java/org/motechproject/mots/repository/CommunityHealthWorkerRepositoryIntegrationTest.java
src/test/java/org/motechproject/mots/testbuilder/ChiefdomDataBuilder.java
src/test/java/org/motechproject/mots/testbuilder/CommunityDataBuilder.java
src/test/java/org/motechproject/mots/testbuilder/CommunityHealthWorkerDataBuilder.java
src/test/java/org/motechproject/mots/testbuilder/DistrictDataBuilder.java
src/test/java/org/motechproject/mots/testbuilder/FacilityDataBuilder.java

MOTS-88: Added pagination and search of community health workers on the backend side.
Added endpoint GET /searchChw to Finds CommunityHealthWorkers matching all of the provided parameters. If there are no parameters, return all CommunityHealthWorkers.
https://applab.atlassian.net/browse/MOTS-88

MOTS-88: Added pagination and search of community health workers

---

src/main/java/org/motechproject/mots/repository/custom/impl/CommunityHealthWorkerRepositoryImpl.java
src/main/java/org/motechproject/mots/service/CommunityHealthWorkerService.java
src/main/java/org/motechproject/mots/web/CommunityHealthWorkerController.java
src/test/java/org/motechproject/mots/repository/CommunityHealthWorkerRepositoryIntegrationTest.java
src/webapp/js/actions/index.js
src/webapp/js/container/chw-table.js
src/webapp/js/reducers/tables-data/tables_data_initial_state.js
src/webapp/js/reducers/tables-data/tables_data_reducer.js
src/webapp/js/utils/react-table-search-params.js

- reworked backend to use 'contains' as opposed to 'equals' action
- implemented custom manual filtering on frontend
- fixed tests

MOTS-228 Handle CHW screen pagination/filtering/searching

---

src/main/java/org/motechproject/mots/domain/AssignedCourse.java
src/main/java/org/motechproject/mots/domain/AssignedModules.java
src/main/java/org/motechproject/mots/domain/BaseEntity.java
src/main/java/org/motechproject/mots/domain/BaseTimestampedEntity.java
src/main/java/org/motechproject/mots/domain/CallDetailRecord.java
src/main/java/org/motechproject/mots/domain/Choice.java
src/main/java/org/motechproject/mots/domain/CommunityHealthWorker.java
src/main/java/org/motechproject/mots/domain/Incharge.java
src/main/java/org/motechproject/mots/domain/IvrConfig.java
src/main/java/org/motechproject/mots/domain/IvrObject.java
src/main/java/org/motechproject/mots/domain/JasperTemplate.java
src/main/java/org/motechproject/mots/domain/JasperTemplateParameter.java
src/main/java/org/motechproject/mots/domain/Location.java
src/main/java/org/motechproject/mots/domain/ModuleProgress.java
src/main/java/org/motechproject/mots/domain/QuestionResponse.java
src/main/java/org/motechproject/mots/domain/UnitProgress.java
src/main/java/org/motechproject/mots/domain/security/User.java
src/main/java/org/motechproject/mots/domain/security/UserLog.java
src/main/java/org/motechproject/mots/domain/security/UserRole.java
src/main/java/org/motechproject/mots/repository/UserLogRepository.java
src/main/java/org/motechproject/mots/security/CustomTokenEnhancer.java
src/main/java/org/motechproject/mots/security/TokenConfiguration.java
src/main/java/org/motechproject/mots/service/UserLogService.java
src/main/resources/db/changelog/20180219_1840.mysql.sql
src/main/resources/db/changelog/liquibase-changelog.xml
src/test/java/org/motechproject/mots/repository/BaseCrudRepositoryIntegrationTest.java
src/test/java/org/motechproject/mots/repository/CommunityHealthWorkerRepositoryIntegrationTest.java

@pmuchowski , @kkaczmarczyk : We decided to store all token requests (including refreshing tokens) for now so we can start working on User Log Report, but I created a ticket https://applab.atlassian.net/browse/MOTS-280
to extend DefaultTokenServices and determine if a refresh token is used.

MOTS-246: Store user login and logout dates

---

src/main/java/org/motechproject/mots/repository/InchargeRepository.java
src/main/java/org/motechproject/mots/repository/custom/InchargeRepositoryCustom.java
src/main/java/org/motechproject/mots/repository/custom/impl/InchargeRepositoryImpl.java
src/main/java/org/motechproject/mots/service/InchargeService.java
src/main/java/org/motechproject/mots/web/InchargeController.java
src/test/java/org/motechproject/mots/repository/InchargeRepositoryIntegrationTest.java
src/test/java/org/motechproject/mots/testbuilder/InchargeDataBuilder.java

Added pagination and search of Incharges on the backend side.
Added endpoint GET incharge/search to finds Incharges matching all of the provided parameters.
If there are no parameters, return all Incharges.
Fixed sorting in pagination.
Added integration tests.
https://applab.atlassian.net/browse/MOTS-89
https://applab.atlassian.net/browse/MOTS-278

MOTS-89: Added pagination and search of Incharges

---

src/webapp/js/actions/index.js
src/webapp/js/container/chw-table.js
src/webapp/js/container/incharge-table.js
src/webapp/js/reducers/tables-data/tables_data_initial_state.js
src/webapp/js/reducers/tables-data/tables_data_reducer.js

+ non-sortable Action column in CHW/Incharge tables

MOTS-287 Frontend: Incharge table pagination/filtering

---

src/main/java/org/motechproject/mots/web/InchargeController.java

MOTS-89: Fixed parameter name in Incharge controller
https://applab.atlassian.net/browse/MOTS-89

MOTS-89: Fixed parameter name in Incharge controller

---

src/main/java/org/motechproject/mots/mapper/LocationMapper.java
src/main/java/org/motechproject/mots/repository/ChiefdomRepository.java
src/main/java/org/motechproject/mots/repository/CommunityRepository.java
src/main/java/org/motechproject/mots/repository/DistrictRepository.java
src/main/java/org/motechproject/mots/repository/FacilityRepository.java
src/main/java/org/motechproject/mots/repository/custom/ChiefdomRepositoryCustom.java
src/main/java/org/motechproject/mots/repository/custom/CommunityRepositoryCustom.java
src/main/java/org/motechproject/mots/repository/custom/DistrictRepositoryCustom.java
src/main/java/org/motechproject/mots/repository/custom/FacilityRepositoryCustom.java
src/main/java/org/motechproject/mots/repository/custom/impl/BaseRepositoryImpl.java
src/main/java/org/motechproject/mots/repository/custom/impl/ChiefdomRepositoryImpl.java
src/main/java/org/motechproject/mots/repository/custom/impl/CommunityHealthWorkerRepositoryImpl.java
src/main/java/org/motechproject/mots/repository/custom/impl/CommunityRepositoryImpl.java
src/main/java/org/motechproject/mots/repository/custom/impl/DistrictRepositoryImpl.java
src/main/java/org/motechproject/mots/repository/custom/impl/FacilityRepositoryImpl.java
src/main/java/org/motechproject/mots/repository/custom/impl/InchargeRepositoryImpl.java
src/main/java/org/motechproject/mots/service/LocationService.java
src/main/java/org/motechproject/mots/web/CommunityHealthWorkerController.java
src/main/java/org/motechproject/mots/web/InchargeController.java
src/main/java/org/motechproject/mots/web/LocationController.java
src/test/java/org/motechproject/mots/repository/ChiefdomRepositoryIntegrationTest.java
src/test/java/org/motechproject/mots/repository/CommunityRepositoryIntegrationTest.java
src/test/java/org/motechproject/mots/repository/DistrictRepositoryIntegrationTest.java
src/test/java/org/motechproject/mots/repository/FacilityRepositoryIntegrationTest.java

Added pagination and search of locations.
Also added constans of parameters.
https://applab.atlassian.net/browse/MOTS-264

Mots 264: Added pagination and search of locations

---

src/webapp/js/components/assign-modules.js

- additionally I made the whole screen narrower

MOTS-198 Clear Value on Assign Module page causes error in console

---

src/main/java/org/motechproject/mots/repository/UserRepository.java
src/main/java/org/motechproject/mots/repository/custom/UserRepositoryCustom.java
src/main/java/org/motechproject/mots/repository/custom/impl/BaseRepositoryImpl.java
src/main/java/org/motechproject/mots/repository/custom/impl/UserRepositoryImpl.java
src/main/java/org/motechproject/mots/service/UserService.java
src/main/java/org/motechproject/mots/web/UserController.java
src/test/java/org/motechproject/mots/repository/UserRepositoryIntegrationTest.java
src/test/java/org/motechproject/mots/testbuilder/UserDataBuilder.java
src/test/java/org/motechproject/mots/testbuilder/UserRoleDataBuilder.java

Added pagination and search of users.
Added integration tests of searching users.
https://applab.atlassian.net/browse/MOTS-302

Mots 302 users table pagination search

---

mobile/components/UserForm.js
src/main/java/org/motechproject/mots/constants/ValidationMessages.java
src/main/java/org/motechproject/mots/dto/UserDto.java
src/main/java/org/motechproject/mots/mapper/UserMapper.java
src/main/java/org/motechproject/mots/service/UserService.java
src/main/java/org/motechproject/mots/validate/annotations/UsernameUniqueness.java
src/main/java/org/motechproject/mots/validate/constraintvalidators/user/UsernameValidator.java
src/main/java/org/motechproject/mots/web/UserController.java
src/webapp/js/components/form-field.js
src/webapp/js/components/user-edit.js
src/webapp/js/components/user-form.js

- validation on backend and frontend
- don't require password during edition

MOTS-250 & MOTS-328: Improvements to User form

---

src/main/java/org/motechproject/mots/service/UserService.java
src/main/java/org/motechproject/mots/validate/constraintvalidators/user/UsernameValidator.java
src/main/java/org/motechproject/mots/web/UserController.java
src/webapp/js/components/user-form.js

-fix validator for new users
-don't encode password if it's not changed

user flow fixes

---

src/webapp/js/actions/index.js
src/webapp/js/components/locations.js
src/webapp/js/container/locations-table.js
src/webapp/js/reducers/tables-data/tables_data_initial_state.js
src/webapp/js/reducers/tables-data/tables_data_reducer.js

Added front-end search and pagination of locations.
Fixed responsive view of location table.
https://applab.atlassian.net/browse/MOTS-342

MOTS-342: Added frontend search and pagination of locations.

---

src/main/java/org/motechproject/mots/constants/ValidationMessages.java
src/main/java/org/motechproject/mots/dto/UserProfileDto.java
src/main/java/org/motechproject/mots/errorhandling/ErrorResponse.java
src/main/java/org/motechproject/mots/errorhandling/GlobalErrorHandling.java
src/main/java/org/motechproject/mots/service/UserService.java
src/main/java/org/motechproject/mots/validate/annotations/NewPasswordsMatch.java
src/main/java/org/motechproject/mots/validate/constraintvalidators/UserProfileDtoNewPasswordsMatchValidator.java
src/main/java/org/motechproject/mots/web/UserController.java

Added backend validation to User Profile screen. Id, Passwords, Email must be valid.
https://applab.atlassian.net/browse/MOTS-371

MOTS-371: Added backend validation to User Profile screen.

---

src/webapp/js/components/group-assign-modules.js

Frontend validation on Assign Modules to a District page
https://applab.atlassian.net/browse/MOTS-293

MOTS-293: Frontend validation on Assign Modules to a District page

---

mobile/components/HealthWorkersForm.js
src/main/java/org/motechproject/mots/constants/ValidationMessages.java
src/main/java/org/motechproject/mots/dto/CommunityHealthWorkerDto.java
src/main/java/org/motechproject/mots/validate/annotations/PastDate.java
src/main/java/org/motechproject/mots/validate/constraintvalidators/PastDateFormatValidator.java
src/webapp/js/components/health-workers-form.js

Front-end and Back-end validation to day of birth.
https://applab.atlassian.net/browse/MOTS-364

Mots 364: Front-end and Back-end validation to day of birth.

---

src/webapp/js/components/app.js
src/webapp/js/utils/api-client.js

Changed - Alerts disappear when user click 'x' button.
https://applab.atlassian.net/browse/MOTS-340

MOTS-340: Changed - Alerts disappear when user click 'x' button.

---

src/main/java/org/motechproject/mots/constants/ValidationMessages.java
src/main/java/org/motechproject/mots/dto/CommunityCreationDto.java
src/main/java/org/motechproject/mots/dto/CommunityExtendedInfoDto.java
src/main/java/org/motechproject/mots/dto/FacilityCreationDto.java
src/main/java/org/motechproject/mots/dto/FacilityExtendedInfoDto.java
src/main/java/org/motechproject/mots/dto/InchargeDto.java
src/main/java/org/motechproject/mots/mapper/LocationMapper.java
src/main/java/org/motechproject/mots/repository/CommunityRepository.java
src/main/java/org/motechproject/mots/repository/FacilityRepository.java
src/main/java/org/motechproject/mots/validate/annotations/AssignFacilityToInchargeUniqueness.java
src/main/java/org/motechproject/mots/validate/annotations/ChiefdomExistence.java
src/main/java/org/motechproject/mots/validate/annotations/CommunityUniqueness.java
src/main/java/org/motechproject/mots/validate/annotations/UniqueFacilityId.java
src/main/java/org/motechproject/mots/validate/constraintvalidators/ChiefdomExistenceValidator.java
src/main/java/org/motechproject/mots/validate/constraintvalidators/CommunityUniquenessValidator.java
src/main/java/org/motechproject/mots/validate/constraintvalidators/FacilityUniquenessValidator.java
src/main/java/org/motechproject/mots/validate/constraintvalidators/UniqueFacilityIdValidator.java
src/main/java/org/motechproject/mots/validate/constraintvalidators/incharge/InchargeDtoFacilityUniquenessValidator.java
src/main/java/org/motechproject/mots/web/LocationController.java
src/webapp/js/actions/types.js
src/webapp/js/components/community-edit.js
src/webapp/js/components/community-new.js
src/webapp/js/components/facility-edit.js
src/webapp/js/components/facility-new.js

Added validation to create Community and Facility.
Refactor in LocationController.
Adjusted UI to new DTOs of community and facility.
https://applab.atlassian.net/browse/MOTS-351

MOTS: 351 Added validation to create Community and Facility. 

---

src/main/java/org/motechproject/mots/constants/ValidationMessages.java
src/main/java/org/motechproject/mots/domain/Course.java
src/main/java/org/motechproject/mots/domain/Module.java
src/main/java/org/motechproject/mots/domain/MultipleChoiceQuestion.java
src/main/java/org/motechproject/mots/domain/Unit.java
src/main/java/org/motechproject/mots/validate/annotations/IsCorrect.java
src/main/java/org/motechproject/mots/validate/constraintvalidators/IsCorrectValidator.java

Added IsCorrect annotation to validations.
Fixed nested validation if release course.
https://applab.atlassian.net/browse/MOTS-367

MOTS-367: Fixed nested validation if release course and add IsCorrect validation

---

src/main/java/org/motechproject/mots/dto/FacilityDto.java
src/webapp/js/components/health-workers-form.js
src/webapp/js/utils/form-utils.js

-make facility, chiefdom and district required in the form

MOTS-317: -add supervisor display to CHW form

---

mobile/src/components/FormField.js
mobile/src/components/HealthWorkersForm.js
mobile/src/utils/form-utils.js

MOTS-405: Mobile CHW form - supervisor name field

---

src/webapp/js/components/app.js
src/webapp/js/components/facility-new.js
src/webapp/js/components/locations.js

Displayed table with Facilities after new adding Facility.
https://applab.atlassian.net/browse/MOTS-360

MOTS-360: Displayed table with Facilities after new adding Facility.

---

src/webapp/js/actions/index.js
src/webapp/js/container/users-table.js
src/webapp/js/reducers/tables-data/tables_data_initial_state.js
src/webapp/js/reducers/tables-data/tables_data_reducer.js
src/webapp/js/utils/react-table-search-params.js

Added frontend search, pagination of Users.
https://applab.atlassian.net/browse/MOTS-404

Mots 404: Frontend users pagination search

---

src/webapp/js/components/locations.js
src/webapp/js/components/sidebar.js

Refactor of Locations Component, fixed states.
https://applab.atlassian.net/browse/MOTS-360

MOTS-360: Refactor of Locations Component, fixed states.

---

src/webapp/js/components/facility-edit.js

https://applab.atlassian.net/browse/MOTS-360

MOTS-360: Moved to facilities when edit facility.

---

src/main/java/org/motechproject/mots/constants/ValidationMessages.java
src/main/java/org/motechproject/mots/dto/FacilityCreationDto.java
src/main/java/org/motechproject/mots/validate/annotations/UniqueFacilityId.java
src/main/java/org/motechproject/mots/validate/constraintvalidators/CommunityUniquenessValidator.java
src/main/java/org/motechproject/mots/validate/constraintvalidators/FacilityUniquenessValidator.java
src/main/java/org/motechproject/mots/validate/constraintvalidators/UniqueFacilityIdValidator.java

https://applab.atlassian.net/browse/MOTS-351

MOTS-351: Fixed validation of edit facility, community.

---

src/webapp/js/components/incharge-form.js

Added Asterisk to mandatory fields in Incharge List.
https://applab.atlassian.net/browse/MOTS-406

MOTS-406: Added Asterisk to mandatory fields in Incharge List

---

package.json
src/webapp/css/main.scss
src/webapp/js/components/modules-form.js

Added tooltips to Manage Modules page.
https://applab.atlassian.net/browse/MOTS-383

MOTS-383: Added tooltips to Manage Modules page.

---

src/webapp/js/utils/form-utils.js

Fixed browser refresh on Incharge and CHW edit pages.
https://applab.atlassian.net/browse/MOTS-403

MOTS-403: Fixed browser refresh on Incharge and CHW edit pages.

---

src/webapp/js/container/users-table.js

https://applab.atlassian.net/browse/MOTS-404

MOTS-404: Fixed sorting role param.

---

mobile/src/components/AssignModulesToChw.js
mobile/src/components/FormField.js
mobile/src/components/ProfileForm.js
mobile/src/reducers/tables-data/tables_data_reducer.js
mobile/src/styles/inputsStyles.js

MOTS-393: Profile edit - password confirmation asterisks

---

src/main/java/org/motechproject/mots/service/CommunityHealthWorkerService.java
src/webapp/css/main.scss
src/webapp/js/components/health-workers-upload.js

- modified way of converting file which breaks staging on staging setup
- stylized upload CSV screen
- made Upload button disabled until file is chosen

MOTS-357 & partly MOTS-439

---

package.json
src/webapp/js/components/modules-form.js

https://applab.atlassian.net/browse/MOTS-383

MOTS-383: Changed tooltips library.

---

src/main/java/org/motechproject/mots/domain/Community.java
src/main/java/org/motechproject/mots/domain/District.java
src/main/java/org/motechproject/mots/domain/Facility.java
src/main/java/org/motechproject/mots/domain/Location.java
src/main/java/org/motechproject/mots/dto/LocationPreviewDto.java
src/main/java/org/motechproject/mots/mapper/LocationMapper.java
src/main/java/org/motechproject/mots/repository/custom/CommunityRepositoryCustom.java
src/main/java/org/motechproject/mots/repository/custom/FacilityRepositoryCustom.java
src/main/java/org/motechproject/mots/repository/custom/impl/CommunityRepositoryImpl.java
src/main/java/org/motechproject/mots/repository/custom/impl/FacilityRepositoryImpl.java
src/main/java/org/motechproject/mots/service/LocationService.java
src/main/java/org/motechproject/mots/web/LocationController.java
src/test/java/org/motechproject/mots/repository/CommunityRepositoryIntegrationTest.java
src/test/java/org/motechproject/mots/repository/FacilityRepositoryIntegrationTest.java
src/webapp/js/components/locations.js

Extend locations table.
https://applab.atlassian.net/browse/MOTS-427

MOTS-427: Extend locations table.

---

src/webapp/js/utils/authorization.js

https://applab.atlassian.net/browse/MOTS-346

MOTS-346: Fixed edit locations when Level 2 user.

---

src/main/java/org/motechproject/mots/repository/JasperTemplateRepository.java
src/main/java/org/motechproject/mots/web/JasperTemplateController.java
src/test/java/org/motechproject/mots/repository/JasperTemplateRepositoryIntegrationTest.java

https://applab.atlassian.net/browse/MOTS-453

MOTS-453: Changed reports order.

---

src/webapp/js/components/assign-modules.js
src/webapp/js/components/csv-upload.js
src/webapp/js/components/form-field.js
src/webapp/js/components/group-assign-modules.js
src/webapp/js/components/health-workers-form.js
src/webapp/js/components/locations.js
src/webapp/js/components/modules-form.js
src/webapp/js/components/mots-confirm-modal.js
src/webapp/js/components/navbar.js
src/webapp/js/components/report.js
src/webapp/js/components/sidebar.js
src/webapp/js/container/chw-table.js
src/webapp/js/container/incharge-table.js
src/webapp/js/container/locations-table.js
src/webapp/js/container/users-table.js

https://applab.atlassian.net/browse/MOTS-209

MOTS-209: Refresh token more often

---

src/main/java/org/motechproject/mots/domain/security/UserPermission.java
src/main/java/org/motechproject/mots/service/CommunityHealthWorkerService.java
src/main/java/org/motechproject/mots/service/InchargeService.java
src/main/resources/db/changelog/20180329_1221.mysql.sql
src/main/resources/db/changelog/liquibase-changelog.xml
src/webapp/js/components/csv-upload.js
src/webapp/js/components/sidebar.js
src/webapp/js/utils/authorization.js

https://applab.atlassian.net/browse/MOTS-457

MOTS-457: Fixed chw read role. Added upload csv right to Level 2 role.

---

src/webapp/js/components/csv-upload.js
src/webapp/js/components/sidebar.js

- added border to CSV upload screen component
- fixed inconsistent borders in menu

styling fixes:

---

src/webapp/js/components/app.js

Fixed footer displayed only on the main page.

MOTS-558 fixed footer

---

mobile/src/components/Footer.js

MOTS-558 Fixed footer added on mobile app

---

mobile/src/components/auth/RequireAuth.js
mobile/src/reducers/auth_reducer.js

* the Date object was not properly persisted by redux-persist. Switched to time (integer)
* after closing and opening the app, user was always logged out. restored previous behaviour

MOTS-601: Fix persisting login data

---

src/main/java/org/motechproject/mots/service/UserService.java

when trying to add already existing role

MOTS-614 Change the content of error message displayed
